name: Keep Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Run every 14 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Site
        run: curl -I https://drawchain.logiclane.online/
